#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
echo '🏗️👷 Styling, testing and building your project before committing'

# Check ESLint Standards
yarn lint ||
(
    echo '🙈👷🔨❌ Yoo, your code looks disgusting. Check linter 🙈👷🔨❌
          Run yarn lint, add changes and try commit again.';
    false;
)

# If there is no error linter, the codes will be commited
echo '🎉🎉🎉🎉 Yeayy, there is no errors in your codes... I am committing this now. ✨🚀🏄‍♂️🍻'

npx lint-staged